/**
 * API Client for Activity
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all activities
 */
export const getAllActivities = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/activities${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch activities`);
  }

  return response.json();
};

/**
 * Get single activity by ID
 */
export const getActivityById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/activities/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch activity`);
  }

  return response.json();
};

/**
 * Create new activity
 */
export const createActivity = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/activities`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create activity`);
  }

  return response.json();
};

/**
 * Update activity (partial update)
 */
export const updateActivity = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/activities/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update activity`);
  }

  return response.json();
};

/**
 * Delete activity
 */
export const deleteActivity = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/activities/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete activity`);
  }

  return response.json();
};

export default {
  getAllActivities,
  getActivityById,
  createActivity,
  updateActivity,
  deleteActivity
};
