/**
 * API Client for Category
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all category
 */
export const getAllCategory = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/category${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch category`);
  }

  return response.json();
};

/**
 * Get single category by ID
 */
export const getCategoryById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/category/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch category`);
  }

  return response.json();
};

/**
 * Create new category
 */
export const createCategory = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/category`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create category`);
  }

  return response.json();
};

/**
 * Update category (partial update)
 */
export const updateCategory = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/category/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update category`);
  }

  return response.json();
};

/**
 * Delete category
 */
export const deleteCategory = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/category/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete category`);
  }

  return response.json();
};

export default {
  getAllCategory,
  getCategoryById,
  createCategory,
  updateCategory,
  deleteCategory
};
