/**
 * API Clients Index
 * Auto-generated by offbyte
 */

import pAPI from './p.js';
import activityAPI from './activity.js';
import showHostOptionAPI from './showHostOption.js';
import mousePoAPI from './mousePo.js';
import categoryAPI from './category.js';
import questionAPI from './question.js';

export {
  pAPI,
  activityAPI,
  showHostOptionAPI,
  mousePoAPI,
  categoryAPI,
  questionAPI,
};

export default {
  p: pAPI,
  activity: activityAPI,
  showHostOption: showHostOptionAPI,
  mousePo: mousePoAPI,
  category: categoryAPI,
  question: questionAPI,
};
