/**
 * API Client for MousePo
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all mousePos
 */
export const getAllMousePos = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/mousePos${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch mousePos`);
  }

  return response.json();
};

/**
 * Get single mousePo by ID
 */
export const getMousePoById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/mousePos/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch mousePo`);
  }

  return response.json();
};

/**
 * Create new mousePo
 */
export const createMousePo = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/mousePos`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create mousePo`);
  }

  return response.json();
};

/**
 * Update mousePo (partial update)
 */
export const updateMousePo = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/mousePos/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update mousePo`);
  }

  return response.json();
};

/**
 * Delete mousePo
 */
export const deleteMousePo = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/mousePos/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete mousePo`);
  }

  return response.json();
};

export default {
  getAllMousePos,
  getMousePoById,
  createMousePo,
  updateMousePo,
  deleteMousePo
};
