/**
 * API Client for P
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all players
 */
export const getAllPlayers = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/players${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch players`);
  }

  return response.json();
};

/**
 * Get single p by ID
 */
export const getPById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/players/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch p`);
  }

  return response.json();
};

/**
 * Create new p
 */
export const createP = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/players`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create p`);
  }

  return response.json();
};

/**
 * Update p (partial update)
 */
export const updateP = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/players/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update p`);
  }

  return response.json();
};

/**
 * Delete p
 */
export const deleteP = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/players/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete p`);
  }

  return response.json();
};

export default {
  getAllPlayers,
  getPById,
  createP,
  updateP,
  deleteP
};
