/**
 * API Client for Question
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all questions
 */
export const getAllQuestions = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/questions${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch questions`);
  }

  return response.json();
};

/**
 * Get single question by ID
 */
export const getQuestionById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/questions/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch question`);
  }

  return response.json();
};

/**
 * Create new question
 */
export const createQuestion = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/questions`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create question`);
  }

  return response.json();
};

/**
 * Update question (partial update)
 */
export const updateQuestion = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/questions/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update question`);
  }

  return response.json();
};

/**
 * Delete question
 */
export const deleteQuestion = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/questions/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete question`);
  }

  return response.json();
};

export default {
  getAllQuestions,
  getQuestionById,
  createQuestion,
  updateQuestion,
  deleteQuestion
};
