/**
 * API Client for ShowHostOption
 * Auto-generated by offbyte
 */

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000';

/**
 * Get all showHostOptions
 */
export const getAllShowHostOptions = async (params = {}) => {
  const query = new URLSearchParams(params).toString();
  const url = `${import.meta.env.VITE_API_URL}/api/showHostOptions${query ? '?' + query : ''}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch showHostOptions`);
  }

  return response.json();
};

/**
 * Get single showHostOption by ID
 */
export const getShowHostOptionById = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/showHostOptions/${id}`;
  
  const response = await fetch(url, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch showHostOption`);
  }

  return response.json();
};

/**
 * Create new showHostOption
 */
export const createShowHostOption = async (data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/showHostOptions`;
  
  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to create showHostOption`);
  }

  return response.json();
};

/**
 * Update showHostOption (partial update)
 */
export const updateShowHostOption = async (id, data) => {
  const url = `${import.meta.env.VITE_API_URL}/api/showHostOptions/${id}`;
  
  const response = await fetch(url, {
    method: 'PATCH',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify(data)
  });

  if (!response.ok) {
    throw new Error(`Failed to update showHostOption`);
  }

  return response.json();
};

/**
 * Delete showHostOption
 */
export const deleteShowHostOption = async (id) => {
  const url = `${import.meta.env.VITE_API_URL}/api/showHostOptions/${id}`;
  
  const response = await fetch(url, {
    method: 'DELETE',
    headers: {
      'Content-Type': 'application/json'
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to delete showHostOption`);
  }

  return response.json();
};

export default {
  getAllShowHostOptions,
  getShowHostOptionById,
  createShowHostOption,
  updateShowHostOption,
  deleteShowHostOption
};
